name: cirilla
description: Cirilla - Multipurpose Flutter Wordpress App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  feather_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0
  google_fonts: ^2.0.0

  # UI
  ui:
    path: ../ui

  shared_preferences: ^2.0.3
  shared_preferences_web: ^2.0.0

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

  provider:

  dio: ^4.0.0-prev3

  crypto: ^3.0.0

  flutter_spinkit: ^4.1.2

  json_annotation: ^3.1.1

  # Slideshow and image gallery
  flutter_swiper: ^1.1.6
  photo_view: ^0.10.3

  dotted_border: ^2.0.0-nullsafety.0

  flutter_html:
    git: https://github.com/Sub6Resources/flutter_html.git

  google_maps_flutter: ^2.0.1
  google_maps_flutter_web: ^0.2.1

  url_launcher: ^6.0.2

  # Drawer animation
  flutter_zoom_drawer:
    git: https://github.com/AppCheap/flutter_zoom_drawer.git

  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^1.0.2

  # Add the Firebase Auth dependencies
  firebase_auth: ^1.0.1
  pin_code_fields: ^7.0.0

  # Sign In Google
  google_sign_in: ^5.0.1

  # Sign In Apple
  sign_in_with_apple: ^3.0.0

  # Sign In facebook
  flutter_facebook_auth: ^3.1.1

  # Text animations
  animated_text_kit: ^4.0.0

  # Webview flutter
  webview_flutter: ^2.0.2

  # Format date time
  intl: ^0.17.0

  # Share content
  share: ^2.0.1

  # Shimmer loading
  shimmer: ^2.0.0-nullsafety.0

  # Play audio
  just_audio: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.1
  mobx_codegen: ^1.1.2
  json_serializable: ^3.5.1

  # App's launcher icon
  flutter_launcher_icons: ^0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: google_fonts/Poppins-Regular.ttf
        - asset: google_fonts/Poppins-Light.ttf
          weight: 300
        - asset: google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: google_fonts/Poppins-SemiBold.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/lang/
    - assets/images/
